#!/usr/bin/env bash

target_type=local

## Destination settings
image_path="$HOME/Pictures/Screenshots/$(date +'%m.%Y')"
video_path="$HOME/Videos/Screencasts/$(date +'%m.%Y')"
text_path="$HOME/Documents/ClipboardSaves/$(date +'%m.%Y')"

### Qaulity Screencast settings

# It may be usefull to change qulity of screencast for diffrent targets
# If you don't care about video size just don't touch this settings :)

# Only for filename, see video_filemask in  ~/.config/heyteiler/config
ffmpeg_type="mp4" 
# ffmpeg video capture settings for fullscreen mode (read more in ffmpeg docs)
ffmpeg_video_fullscreen="-f pulse -ac 2 -i default -r 30 -c:v libx264 -preset slow -crf 18 -c:a libvorbis "
# sometimes it is usefull to change settings for area mode
ffmpeg_video_area="${ffmpeg_video_fullscreen}"

# You may change screen resolution for this target (it will changed back after
# stop recording)
#resolution=800x600
